apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend-deployment
  labels:
    app: node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
      - name: node-backend
        image: us-central1-docker.pkg.dev/prefab-surfer-447104-r9/spotify/backend-nodejs:1.0.0
        ports:
        - containerPort: 3001
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: OPENAI_API_KEY
          - name: SPOTIFY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: spotify-secret
                key: SPOTIFY_CLIENT_ID
          - name: SPOTIFY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: spotify-secret
                key: SPOTIFY_CLIENT_SECRET
          - name: SPOTIFY_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: spotify-secret
                key: SPOTIFY_REDIRECT_URI

---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
