apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-frontend-deployment
  labels:
    app: next-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-frontend
  template:
    metadata:
      labels:
        app: next-frontend
    spec:
      containers:
      - name: next-frontend
        image: us-central1-docker.pkg.dev/prefab-surfer-447104-r9/spotify/frontend-nextjs:1.0.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: next-frontend-service
spec:
  selector:
    app: next-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
