apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi-deployment
  labels:
    app: python-fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-fastapi
  template:
    metadata:
      labels:
        app: python-fastapi
    spec:
      containers:
      - name: python-fastapi
        image: us-central1-docker.pkg.dev/prefab-surfer-447104-r9/spotify/python-fastapi:v1
        ports:
        - containerPort: 8000
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8000
        #   initialDelaySeconds: 3
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8000
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-service
spec:
  selector:
    app: python-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
